### PR TITLE
Issue 29: More natural links

### LINKED ISSUE #29: more natural links to resources (e.g. white paper or profile) when that is what narrative needs. Rather than using #further-reading secondary stop

### PR DESCRIPTION
**Pull request by GumptionWare**
Document links should be all there, but most recorded presentations links (from https://wiki.ihe.net/index.php/Current_Published_ITI_Educational_Materials#Publication_and_Discovery) are broken (and noted as such in my edits).

### CODE REVIEW

**Review by JohnMoehrke — CHANGES_REQUESTED** [review]
thanks for the work. In reviewing it, I think we can have more helpful (modern) links.
- DSUB can link to the profiles publication http://profiles.ihe.net/ITI/TF/Volume1/ch-26.html
- the presentations that were on the FTP are now in github https://github.com/IHE/IT-Infrastructure/tree/master/Presentations
- add links to the IHE Youtube channel recording of a given presentation (new location for webinars) https://www.youtube.com/channel/UC_7Rx9MracVwqVXDOH8Hj5Q
- white papers and handbooks http://profiles.ihe.net/ITI/

**Comment by JohnMoehrke** [comment]
given the massive change @DavidPyke did to the text... this pull request likely needs to be re-submitted, in addition to the change I requested above.

**Comment by JohnMoehrke** [comment]
I reverted out daves changes, so your pull request will fit better. However I still would like the changes I recommended be made.

**Comment by JohnMoehrke** [comment]
we can review this change on the call today?

**Comment by JohnMoehrke** [comment]
@GumptionWare are you going to make the requested changes to this pull request?

**Comment by JohnMoehrke** [comment]
@GumptionWare can you update this? Are you okay with updating this branch, or should we accept this pull-request and you can make the updates to a new pull-request?

**Comment by GumptionWare** [comment]
Resolved merge conflicts (2 of them), but have NOT yet incorporated John's suggestions (above). Working on that now.

**Pull request merged**
